-- revenue generated by male vs. female customers
select gender, SUM (purchase_amount) as revenue
from customer_behavior
group by gender

--customers who used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount
from customer_behavior
where discount_applied = 'yes' and purchase_amount >=(select AVG (purchase_amount) from customer_behavior)

--average review rating
select item_purchased, ROUND(AVG (review_rating::numeric),2) as "average product rating"
from customer_behavior
group by item_purchased
order by avg (review_rating) desc 
limit 5

--average purchase amount between standard and express shipping
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer_behavior
where shipping_type in ('Standard','Express')
group by shipping_type

--average spend and total revenue between subscribers and non-subscribers
select subscription_status, COUNT (customer_id) as total_customers,
ROUND (AVG (purchase_amount),2) as avg_spend, 
ROUND (SUM (purchase_amount),2) as total_revenue
from customer_behavior
group by subscription_status
order by total_revenue, avg_spend desc

--top 5 products with highest percentage of purchases with discounts applied
select item_purchased,
ROUND(100 *SUM (CASE WHEN discount_applied = 'Yes'THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer_behavior
group by item_purchased
order by discount_rate desc
limit 5

--customer segmentation 
with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer_behavior)

select customer_segment, COUNT(*) as "Number of Customers"
from customer_type
group by customer_segment

--top 3 most purchased products within each category
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER () over (partition by category order by count (customer_id) DESC) as item_rank
from customer_behavior
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3

--repeat buyers likely to subscribe 
select subscription_status, 
count (customer_id) as repeat_buyers
from customer_behavior
where previous_purchases > 5
group by subscription_status

--revenue contribution of each age group
select age_group,
SUM (purchase_amount) as total_revenue
from customer_behavior
group by age_group
order by total_revenue desc
